version: "3.8"

services:
  traefik:
    image: traefik:v3.1.4
    command:
      - "--api.insecure=false"
      - "--providers.docker=true" 
      - "--providers.docker.swarmMode=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entryPoints.web.http.redirections.entrypoint.scheme=https"
      - "--certificatesresolvers.letsencrypt.acme.tlschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.email=summarybuddy@gmail.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json"
      - "--log.level=INFO"
      - "--accesslog=true"
      - "--api.dashboard=true"
    ports:
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 3000
        published: 3000
        protocol: tcp
        mode: host
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "traefik-certificates:/letsencrypt"
  frontend:
    image: ${IMAGE_FULL_URL}
    container_name: ${DOCKERHUB_IMAGE_NAME}
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - '80:80'
    env_file: .env
    labels:
      - traefik.enable=true
      - traefik.http.services.summarybuddy.loadbalancer.server.port=3000
      - traefik.http.routers.summarybuddy.entrypoints=websecure
      - traefik.http.routers.summarybuddy.rule=Host(`hello.summary-buddy.p-e.kr`)
      - traefik.http.routers.summarybuddy.middlewares=summarybuddy-stripprefix
      - traefik.http.routers.summarybuddy.tls.certresolver=letsencrypt